// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type ProcessInfo struct {
	ID                     int64            `json:"id"`
	UserID                 int64            `json:"user_id"`
	ProcessID              int64            `json:"process_id"`
	ParentProcessID        int64            `json:"parent_process_id"`
	ProcessName            string           `json:"process_name"`
	ThreadCount            int64            `json:"thread_count"`
	HandleCount            int64            `json:"handle_count"`
	BasePriority           int32            `json:"base_priority"`
	CreateTime             pgtype.Timestamp `json:"create_time"`
	UserTime               int64            `json:"user_time"`
	KernelTime             int64            `json:"kernel_time"`
	WorkingSetSize         int64            `json:"working_set_size"`
	PeakWorkingSetSize     int64            `json:"peak_working_set_size"`
	VirtualSize            int64            `json:"virtual_size"`
	PeakVirtualSize        int64            `json:"peak_virtual_size"`
	PagefileUsage          int64            `json:"pagefile_usage"`
	PeakPagefileUsage      int64            `json:"peak_pagefile_usage"`
	PageFaultCount         int64            `json:"page_fault_count"`
	ReadOperationCount     int64            `json:"read_operation_count"`
	WriteOperationCount    int64            `json:"write_operation_count"`
	OtherOperationCount    int64            `json:"other_operation_count"`
	ReadTransferCount      int64            `json:"read_transfer_count"`
	WriteTransferCount     int64            `json:"write_transfer_count"`
	OtherTransferCount     int64            `json:"other_transfer_count"`
	CurrentProcessAddress  pgtype.Text      `json:"current_process_address"`
	NextProcessAddress     pgtype.Text      `json:"next_process_address"`
	PreviousProcessAddress pgtype.Text      `json:"previous_process_address"`
	CreatedAt              pgtype.Timestamp `json:"created_at"`
	UpdatedAt              pgtype.Timestamp `json:"updated_at"`
}

type User struct {
	ID        int64            `json:"id"`
	Name      string           `json:"name"`
	Email     string           `json:"email"`
	Password  string           `json:"password"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
}
