// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	// Process Info Queries
	CreateProcessInfo(ctx context.Context, arg CreateProcessInfoParams) (ProcessInfo, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteProcessInfo(ctx context.Context, arg DeleteProcessInfoParams) error
	DeleteUser(ctx context.Context, id int64) error
	GetProcessInfo(ctx context.Context, arg GetProcessInfoParams) (ProcessInfo, error)
	GetProcessInfosByProcessId(ctx context.Context, arg GetProcessInfosByProcessIdParams) ([]ProcessInfo, error)
	GetProcessInfosByUser(ctx context.Context, userID int64) ([]ProcessInfo, error)
	GetUser(ctx context.Context, id int64) (User, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUsers(ctx context.Context) ([]User, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
