// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	// ============================================
	// Statistics and Analytics
	// ============================================
	CountUserProcesses(ctx context.Context, userID pgtype.Int8) (int64, error)
	CountUserQueries(ctx context.Context, userID pgtype.Int8) (int64, error)
	CountUserSnapshots(ctx context.Context, userID pgtype.Int8) (int64, error)
	// ============================================
	// Process Info Queries
	// ============================================
	CreateProcessInfo(ctx context.Context, arg CreateProcessInfoParams) (ProcessInfo, error)
	// ============================================
	// Process Queries (Query by PID history)
	// ============================================
	CreateProcessQuery(ctx context.Context, arg CreateProcessQueryParams) (ProcessQuery, error)
	// ============================================
	// Process Snapshots Queries
	// ============================================
	CreateProcessSnapshot(ctx context.Context, arg CreateProcessSnapshotParams) (ProcessSnapshot, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteProcessInfo(ctx context.Context, id int64) error
	DeleteProcessSnapshot(ctx context.Context, id int64) error
	DeleteUser(ctx context.Context, id int64) error
	GetMostQueriedProcesses(ctx context.Context, arg GetMostQueriedProcessesParams) ([]GetMostQueriedProcessesRow, error)
	GetProcessInfo(ctx context.Context, id int64) (ProcessInfo, error)
	GetProcessInfoBySnapshotAndPID(ctx context.Context, arg GetProcessInfoBySnapshotAndPIDParams) (ProcessInfo, error)
	GetProcessInfosByProcessID(ctx context.Context, arg GetProcessInfosByProcessIDParams) ([]ProcessInfo, error)
	GetProcessInfosBySnapshot(ctx context.Context, snapshotID int64) ([]ProcessInfo, error)
	GetProcessInfosByUser(ctx context.Context, userID pgtype.Int8) ([]ProcessInfo, error)
	GetProcessQueriesByPID(ctx context.Context, arg GetProcessQueriesByPIDParams) ([]ProcessQuery, error)
	GetProcessQueriesBySnapshot(ctx context.Context, snapshotID int64) ([]ProcessQuery, error)
	GetProcessQueriesByUser(ctx context.Context, userID pgtype.Int8) ([]ProcessQuery, error)
	GetProcessQuery(ctx context.Context, id int64) (ProcessQuery, error)
	GetProcessSnapshot(ctx context.Context, id int64) (ProcessSnapshot, error)
	GetProcessSnapshotsByType(ctx context.Context, arg GetProcessSnapshotsByTypeParams) ([]ProcessSnapshot, error)
	GetProcessSnapshotsByUser(ctx context.Context, userID pgtype.Int8) ([]ProcessSnapshot, error)
	GetSnapshotStatistics(ctx context.Context, userID pgtype.Int8) (GetSnapshotStatisticsRow, error)
	GetUser(ctx context.Context, id int64) (User, error)
	GetUserByName(ctx context.Context, name string) (User, error)
	GetUsers(ctx context.Context) ([]User, error)
	UpdateNextProcess(ctx context.Context, arg UpdateNextProcessParams) (ProcessInfo, error)
	UpdatePreviousProcess(ctx context.Context, arg UpdatePreviousProcessParams) (ProcessInfo, error)
	UpdateProcessSnapshotCount(ctx context.Context, arg UpdateProcessSnapshotCountParams) error
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
